Fix lock file with `cargo update`
The error was:

    error: failed to parse lock file at: /home/minoru/src/minoru-fediverse-crawler/Cargo.lock

    Caused by:
      package `base64` is specified twice in the lockfile